spring:
  application:
    name: kotlin-spring-chat-app

  profiles:
    active: local  # ????? local ???? ??

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

jwt:
  secret: mySecretKeyForJWTTokenMustBeLongEnoughForHS512Algorithm
  expiration: 86400000 # 24 hours

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always