spring:
  application:
    name: kotlin-spring-chat-app

  datasource:
    url: jdbc:h2:mem:chatdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

jwt:
  secret: mySecretKeyForJWTTokenMustBeLongEnoughForHS512Algorithm
  expiration: 86400000 # 24 hours

logging:
  level:
    com.example.demo: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always