spring:
  application:
    name: kotlin-spring-chat-app

  profiles:
    active: local  # 기본적으로 local 프로파일 사용

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

jwt:
  secret: mySecretKeyForJWTTokenMustBeLongEnoughForHS512AlgorithmAndShouldBeAtLeast512BitsLongForSecurityPurposes
  expiration: 86400000 # 24 hours

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: true
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.kopringCRUD: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    root: INFO