spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:chatdb}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:chat_user}
    password: ${DB_PASSWORD:your_password}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate  # 운영에서는 validate만 사용
    show-sql: false  # 운영에서는 SQL 로그 비활성화
    properties:
      hibernate:
        format_sql: false

  h2:
    console:
      enabled: false  # 운영에서는 H2 콘솔 비활성화

logging:
  level:
    com.example.kopringCRUD: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    root: WARN