# 공통 설정
spring:
  application:
    name: kotlin-spring-chat-app
  
  # MySQL 데이터베이스 설정
  datasource:
    url: jdbc:mysql://localhost:3306/dbname?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA/Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: create-drop  # 개발용: 시작할 때마다 테이블 재생성
      # ddl-auto: update     # 운영용: 스키마 변경사항만 적용
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: true
        generate_statistics: true
    open-in-view: false

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT 설정 (spring 밖으로 이동)
jwt:
  secret: your-very-long-secret-key-here-make-it-at-least-256-bits-long-for-securityyour-very-long-secret-key-here-make-it-at-least-256-bits-long-for-security
  expiration: 86400000  # 24시간 (밀리초)

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-stacktrace: always
    include-message: always
    include-binding-errors: always

# 로깅 설정 (spring 밖으로 이동)
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.example.kopringCRUD: DEBUG
    org.springframework.transaction: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 스프링 시큐리티 디버깅
debug: false

# 액추에이터 설정 (에러 모니터링용)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always